export enum UserProfileActions {
  CREATE = "PROFILE-CREATION",
  CREATE_FAILURE = "PROFILE-CREATION-FAILURE",
  GET_BY_ID = "GET-PROFILE-BY-ID",
  GET_BY_ID_FAILURE = "GET-PROFILE-BY-ID-FAILURE",
  GET_ALL = "GET-ALL-PROFILES",
  GET_ALL_FAILURE = "GET-ALL-PROFILES-FAILURE",
  UPDATE = "UPDATE-PROFILE",
  UPDATE_FAILURE = "UPDATE-PROFILE-FAILURE",
  DELETE = "DELETE-PROFILE",
  DELETE_FAILURE = "DELETE-PROFILE-FAILURE",
}
